#!/bin/bash
set -e

# K3s Installation Script
# Generated by Terraform

echo "Installing K3s cluster..."

# Master nodes
%{ for idx, ip_list in master_ips ~}
MASTER_${idx + 1}="${ip_list[1][0]}"
%{ endfor ~}

# Worker nodes
%{ for idx, ip_list in worker_ips ~}
WORKER_${idx + 1}="${ip_list[1][0]}"
%{ endfor ~}

# Install on first master
echo "Installing K3s on master node: $MASTER_1"
ssh ubuntu@$MASTER_1 "curl -sfL https://get.k3s.io | sh -"

# Get the token
echo "Getting K3s token..."
TOKEN=$(ssh ubuntu@$MASTER_1 "sudo cat /var/lib/rancher/k3s/server/node-token")

echo "Token: $TOKEN"

# Install on workers
%{ for idx, ip_list in worker_ips ~}
echo "Installing K3s on worker node: ${ip_list[1][0]}"
ssh ubuntu@${ip_list[1][0]} "curl -sfL https://get.k3s.io | K3S_URL=https://$MASTER_1:6443 K3S_TOKEN=$TOKEN sh -"
%{ endfor ~}

echo "K3s cluster installation complete!"
echo "Verify with: ssh ubuntu@$MASTER_1 'sudo kubectl get nodes'"
