#!/bin/bash
set -e

# Portainer Deployment Script for Docker Swarm
# Generated by Terraform

%{ for idx, ip_list in manager_ips ~}
MANAGER_${idx + 1}="${ip_list[0]}"
%{ endfor ~}

echo "Deploying Portainer on Docker Swarm..."

ssh ubuntu@$MANAGER_1 << 'EOF'
    # Create portainer volume
    docker volume create portainer_data

    # Deploy Portainer
    docker service create \
        --name portainer \
        --publish published=9000,target=9000 \
        --publish published=8000,target=8000 \
        --replicas=1 \
        --constraint 'node.role == manager' \
        --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
        --mount type=volume,src=portainer_data,dst=/data \
        portainer/portainer-ce:latest

    echo "Portainer deployed successfully!"
    echo "Access Portainer at: http://$MANAGER_1:9000"
EOF

echo ""
echo "Portainer is now available at: http://$MANAGER_1:9000"
echo "Initial setup required on first login"
