#!/bin/bash
set -e

# Docker Swarm Installation Script
# Generated by Terraform

echo "Installing Docker Swarm cluster..."

# Manager nodes
%{ for idx, ip_list in manager_ips ~}
MANAGER_${idx + 1}="${ip_list[0]}"
%{ endfor ~}

# Worker nodes
%{ for idx, ip_list in worker_ips ~}
WORKER_${idx + 1}="${ip_list[0]}"
%{ endfor ~}

# Function to install Docker
install_docker() {
    local host=$1
    echo "Installing Docker on $host..."
    ssh ubuntu@$host << 'EOF'
        # Update packages
        sudo apt-get update

        # Install dependencies
        sudo apt-get install -y ca-certificates curl gnupg lsb-release

        # Add Docker's official GPG key
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

        # Set up repository
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Install Docker Engine
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

        # Add user to docker group
        sudo usermod -aG docker $USER

        echo "Docker installed successfully"
EOF
}

# Install Docker on all nodes
%{ for idx, ip_list in manager_ips ~}
install_docker "${ip_list[0]}"
%{ endfor ~}

%{ for idx, ip_list in worker_ips ~}
install_docker "${ip_list[0]}"
%{ endfor ~}

# Initialize Swarm on first manager
echo "Initializing Docker Swarm on $MANAGER_1..."
ssh ubuntu@$MANAGER_1 "docker swarm init --advertise-addr $MANAGER_1"

# Get worker join token
echo "Getting worker join token..."
WORKER_TOKEN=$(ssh ubuntu@$MANAGER_1 "docker swarm join-token worker -q")

# Join workers to swarm
%{ for idx, ip_list in worker_ips ~}
echo "Joining worker ${ip_list[0]} to swarm..."
ssh ubuntu@${ip_list[0]} "docker swarm join --token $WORKER_TOKEN $MANAGER_1:2377"
%{ endfor ~}

echo "Docker Swarm cluster setup complete!"
echo "Verify with: ssh ubuntu@$MANAGER_1 'docker node ls'"
